### ISSUE TITLE
[EPIC] - Signup - Informative page about access to location

### ISSUE THREAD

**Issue by Luke-Gurgel** [Luke-Gurgel/flare#26]
After users sign up, it'd be nice to let them know that we're going to need access to their location. 

So instead of transitioning directly to the Home screen after signing up, they should see an informative page about access to their location. 

The point of this page is to increase conversion because if it gets the right message across, users will be more likely to allow access. If they allow access, we can offer more value.

**Acceptance criteria**

- [x] should have a clear message for why we need access to location
- [x] should have 2 buttons: `allow` and `later`
- [x] tapping the `allow` button should bring up the native permission alert. 
- [x] upon allowing permission, should fetch the user's location using the geolocation API with the `enableHighAccuracy` prop set to true, save it in the redux store and proceed to the Home screen
- [x] if the user denies access on the native alert, the same process for tapping the `later` button should be executed
- [x] tapping the `later` button should bring up a confirmation alert letting the user know what they're missing out on.
- [x] the confirmation alert should contain 2 buttons: `later` and `open settings`. 
- [x] tapping the `later` button in the confirmation alert should fetch an approximate location, save it in the redux store and proceed to the Home screen
- [x] tapping the `open settings` button should open the settings app for Flare. If the user doesn't close the app, whenever they come back, we have to check if permission was changed to granted and either fetch the location using the geolocation API or fetch an approximate location. Then, proceed to the Home screen
- [x] there should be error handling for whenever the location cannot be retrieved
